export const FETCH_DELIVERY_DETAILS_BEGIN = 'FETCH_DELIVERY_DETAILS_BEGIN';
export const FETCH_DELIVERY_DETAILS_SUCCESS = 'FETCH_DELIVERY_DETAILS_SUCCESS';
export const FETCH_DELIVERY_DETAILS_FAILURE = 'FETCH_DELIVERY_DETAILS_FAILURE';
