export const FETCH_ORDERS_BEGIN = 'FETCH_ORDERS_BEGIN';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';


export const ADD_ORDER_BEGIN = 'ADD_ORDER_BEGIN';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE';

export const FETCH_TOTAL_REVENEU_BEGIN = 'FETCH_TOTAL_REVENEU_BEGIN';
export const FETCH_TOTAL_REVENEU_SUCCESS = 'FETCH_TOTAL_REVENEU_SUCCESS';
export const FETCH_TOTAL_REVENEU_FAILURE = 'FETCH_TOTAL_REVENEU_FAILURE';
